### ISSUE TITLE
Arduino IDE doesn't verify

### ISSUE THREAD

**Issue by bmwfarmer** [skorokithakis/A6lib#2]
Hello,
Neither of the samples doesn't verify in Arduino IDE 1.6.12.
SMS:4: error: 'A6' does not name a type
 A6 A6l(D8, D9);
 ^
/SMS.ino: In function 'void setup()':
SMS:16: error: 'A6l' was not declared in this scope
     A6l.powerCycle(D0);
     ^
SMS:16: error: 'D0' was not declared in this scope
     A6l.powerCycle(D0);
                    ^
/SMS.ino: In function 'void loop()':
SMS:21: error: 'A6l' was not declared in this scope
     callInfo cinfo = A6l.checkCallStatus();
                      ^
exit status 1
'A6' does not name a type

Great project so.

**Comment by skorokithakis** [comment]
Hello!  
Yes, the problem is that A6 is an analog pin in Arduino. Someone submitted fixes for Arduino, I am going to rename the library to A6lib and also add the other fixes soon.

**Comment by skorokithakis** [comment]
Actually, if someone wanted to submit a PR that renames `A6` to `A6lib`, it would get this done faster.

**Comment by bmwfarmer** [comment]
Confirmed working with IDE 1.6.9, when removed 1024 from SoftwareSerial and capital D from pin definitions. Doesn't comply in IDE 1.6.13.

**Comment by bmwfarmer** [comment]
To save some power in battery powered applications you could stop checking callinfo and monitor modems serial connection. My A6 module sends over serial RING RING, when incoming call is detected. 
<If (SerialString == "RING"){
      callInfo cinfo = A6l.checkCallStatus();
    if (cinfo.direction == DIR_INCOMING && cinfo.number == "123456")
                //do something
    SerialString = " ";
}>

**Comment by skorokithakis** [comment]
I think there was a problem with that approach, but I'll see if I can get it to work, thanks!
